### PR TITLE
Update to latest upstream 7.4.8

### PR DESCRIPTION
**Pull request by jeffsheltren**
https://www.php.net/ChangeLog-7.php#7.4.8

### CODE REVIEW

**Comment by jeffsheltren** [comment]
Patch failed to apply, need to review.

**Comment by jeffsheltren** [comment]
The code in `configure.ac` changed slightly and that was breaking the patch. The patch doesn't appear to be needed, and has been removed upstream in Fedora, so I've removed it here too.

**Comment by jeffsheltren** [comment]
> The [Fedora commit](https://src.fedoraproject.org/rpms/php/c/ac2bd5d87ba623661edc308f4831376f5399e74c?branch=master) that removes patch46 also adds `export PHP_UNAME=$(uname)` near the beginning of `%build`. We should include that as well for completeness.

Thanks for catching. I pushed a commit to include that, although it is building fine on EL7 without it.

**Comment by carlwgeorge** [comment]
php74-7.4.8-1.el7.ius has been published to the testing repository.

**Pull request merged**
