### PR TITLE
Upstream 7.4.14

### PR DESCRIPTION
**Pull request by jeffsheltren**
https://www.php.net/ChangeLog-7.php#7.4.14

### CODE REVIEW

**Comment by lubo** [comment]
Hi. What's the hold-up here?

**Review by LionsAd — APPROVED** [review]

**Comment by jeffsheltren** [comment]
php74-7.4.14-1.el7.ius has been pushed to IUS Testing

**Comment by lubo** [comment]
@jeffsheltren Since this is a patch and a security release, why wasn't it pushed directly to the production? This makes it harder for the users to keep their installations secure.

**Comment by jeffsheltren** [comment]
Hi @lubo -- the standard practice for all IUS updates it to:
1) Require at least one PR approval from another maintainer
2) Once built, move to testing repo for 1 week (https://ius.io/faq#how-long-do-updates-have-to-wait-in-the-testing-repository-before-being-promoted-to-the-main-repository)

If you want things sooner, you can enable the testing repo. I'll be pushing this and the latest 7.3 packages to Stable today or tomorrow.

**Comment by lubo** [comment]
From the linked article:

>We reserve the right to promote package sooner if necessary.

Wouldn't it be appropriate to exercise that right in case of security updates?

**Comment by jeffsheltren** [comment]
Yep, if they are critical I'll do my best to push them faster.

**Comment by jeffsheltren** [comment]
php74-7.4.14-1.el7.ius has been pushed to the main repo.

**Pull request merged**
